### ISSUE TITLE
Crash when opening Wishlist Giveaways page with large wishlists

### ISSUE THREAD

**Issue by BumpShot** [PrOF-kk/SteamGifts#1]
The app closes when you choose to " hide all intered " and  ( from the menu on the left) choose " wishlist " . Only happens on that request.

**Comment by PrOF-kk** [comment]
Which Android version are you using? And how big is your wishlist?
It works correctly for me

**Comment by KRyouCK** [comment]
Mine Android 11. wishlisted 2000+ games. It closes randomly 50/50. It depends which giveaways available to join. And issue is only on "wishlisted" page. There is no issues was with original app (v1.5.13).

**Comment by BumpShot** [comment]
Yea, I'm still on v1.5.13, too.  That is the only version that works for me. I'm On Android 13 .

**Comment by tnka1337** [comment]
All your versions has issue when you click at "Wishlist" with "Hide entered giveaway" option "on". But if you enter it with unchecked option "on" then all OK and you can hide entered again untill u leave this page.
https://github.com/PrOF-kk/SteamGifts/assets/160293855/2b474e45-5fe0-4356-b64b-c010f2080cdc

Let me know if you need any additional info or help.
My steam wishlist page:
https://store.steampowered.com/wishlist/id/tnka/

**Comment by PrOF-kk** [comment]
I've been up all night trying to find the cause for this, I might release a Beta with an app crash reporting tool so I can see what's going on better

**Comment by PrOF-kk** [comment]
[v1.5.17-beta.1](https://github.com/PrOF-kk/SteamGifts/releases/tag/v1.5.17-beta.1) has been released and includes a new Error screen. If it correctly catches the error, please post it here and I'll take a look
