### ISSUE TITLE
Sometimes the app is crazy 

### ISSUE THREAD

**Issue by limonetas** [PrOF-kk/SteamGifts#6]
https://github.com/PrOF-kk/SteamGifts/assets/47794002/5b8140ba-c192-419d-8409-e333e9726d1f

**Comment by PrOF-kk** [comment]
Sorry, I cannot replicate this at all. Does it still happen? If so, how often does it happen and are there steps you take to make it always happen?

**Comment by limonetas** [comment]
> Sorry, I cannot replicate this at all. Does it still happen? If so, how often does it happen and are there steps you take to make it always happen?

I guess it solved itself, or my internet didn't work.
